#!/usr/bin/env python3.12
"""Generate the SatL CLI reference from the binaries' own ``--help`` output.

The only source of truth is the binary: this walks ``satl <path...> --help``
recursively, parses clap's output, and writes one Markdown page per top-level
verb under ``docs/reference/cli/`` (plus ``index.md`` and ``satld.md``).

Why a parser and not ``clap_mangen``/``clap_complete``: adding a generator to
SatL would mean modifying SatL, and the docs repo is deliberately separate.
Parsing is safe here because clap's help output is *strictly positional* —
SatL sets no ``wrap_help``, so the output is byte-identical whatever
``COLUMNS`` says, and every field lives at a fixed indent.

The layout clap emits, and everything this parser leans on:

  * section headers at indent 0: ``Usage:``/``Arguments:``/``Options:``/``Commands:``
  * an entry starts at indent 2 (short flag, positional, subcommand) or
    indent 6 (long-only option, where the ``-x, `` column is blank)
  * an entry's help body is at indent 10, in the "long" template clap picks
    when any argument has a long help or documented possible values
  * in the "short" template the help sits on the entry line itself, after a
    run of two or more spaces

The one trap: in the long template clap emits **whitespace-only lines inside
an entry**, between the help text and the ``[env: ...]``/``[default: ...]``
tail (``--host`` is exactly that shape). Anything that splits entries on blank
lines mis-parses it. So entries are split on *indent*, never on blankness.
"""

from __future__ import annotations

import argparse
import dataclasses
import fnmatch
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - environment problem, not a bug
    sys.exit("gen_cli: PyYAML is missing. Run `make install-deps`.")

BANNER = "<!-- Generated by make gen. Do not edit. -->"

# `Usage:` carries its payload on the same line; the others are bare headers.
USAGE_RE = re.compile(r"^Usage:\s*(.+)$")
HEADER_RE = re.compile(r"^(Arguments|Options|Commands):\s*$")
# Entries start at indent 2 or 6 and never deeper; bodies start at indent >= 7.
ENTRY_RE = re.compile(r"^ {2,6}(?=\S)")
# Trailing clap metadata: `[env: X=]`, `[default: y]`, `[possible values: a, b]`,
# `[alias: cluster]`. Peeled off the tail of a short-template description.
META_TAIL_RE = re.compile(
    r"\s*\[(env|default|possible values|alias(?:es)?|short alias(?:es)?):\s*([^\]]*)\]\s*$"
)
META_LINE_RE = re.compile(
    r"^\[(env|default|possible values|alias(?:es)?|short alias(?:es)?):\s*([^\]]*)\]$"
)
ALIAS_RE = re.compile(r"\s*\[alias(?:es)?:\s*([^\]]+)\]\s*$")
SHORT_RE = re.compile(r"^-([^-,\s])")
LONG_RE = re.compile(r"--([A-Za-z0-9][A-Za-z0-9-]*)")


# --------------------------------------------------------------------------- #
# model
# --------------------------------------------------------------------------- #


@dataclasses.dataclass
class Entry:
    """One row of an ``Arguments:`` or ``Options:`` section."""

    spec: str  # `-p, --publish <PORT>` or `<IMAGE>`
    help: str  # the prose, newlines preserved
    env: str | None = None
    default: str | None = None
    values: list[str] = dataclasses.field(default_factory=list)
    value_help: list[tuple[str, str]] = dataclasses.field(default_factory=list)

    @property
    def long(self) -> str | None:
        m = LONG_RE.search(self.spec)
        return f"--{m.group(1)}" if m else None

    @property
    def short(self) -> str | None:
        m = SHORT_RE.match(self.spec)
        return f"-{m.group(1)}" if m else None

    @property
    def key(self) -> str:
        """Stable identity for set operations: the long flag, else the spec."""
        return self.long or self.spec


@dataclasses.dataclass
class SubCommand:
    name: str
    summary: str
    aliases: list[str] = dataclasses.field(default_factory=list)


@dataclasses.dataclass
class Help:
    """A parsed ``--help`` page."""

    path: list[str]  # ["service", "create"] — the path actually invoked
    about: str
    usage: str
    arguments: list[Entry] = dataclasses.field(default_factory=list)
    options: list[Entry] = dataclasses.field(default_factory=list)
    commands: list[SubCommand] = dataclasses.field(default_factory=list)
    aliases: list[str] = dataclasses.field(default_factory=list)
    children: list["Help"] = dataclasses.field(default_factory=list)

    @property
    def canonical(self) -> list[str]:
        """The path clap itself prints in ``Usage:``.

        ``satl cluster --help`` prints ``Usage: satl swarm ...``: the canonical
        spelling is what keys the visited set, so an alias never produces a
        second page.
        """
        return usage_path(self.usage)

    @property
    def subcommand_required(self) -> bool:
        """``<COMMAND>`` means the bare verb is an error; ``[COMMAND]`` means it runs."""
        return "<COMMAND>" in self.usage


# --------------------------------------------------------------------------- #
# parsing
# --------------------------------------------------------------------------- #


def usage_path(usage: str) -> list[str]:
    """Command path out of a usage line, stopping at the first placeholder."""
    tokens = usage.split()[1:]  # drop the binary name
    path: list[str] = []
    for token in tokens:
        if not re.fullmatch(r"[a-z][a-z0-9-]*", token):
            break
        path.append(token)
    return path


def split_entries(body: list[str]) -> list[list[str]]:
    """Split a section body into entries, keyed on indent alone.

    Blank and whitespace-only lines belong to the entry they sit in — clap puts
    them *inside* one, so treating them as separators is the classic bug.
    """
    entries: list[list[str]] = []
    for line in body:
        if ENTRY_RE.match(line):
            entries.append([line])
        elif entries:
            entries[-1].append(line)
        # lines before the first entry are clap noise; there are none in practice
    return entries


def parse_entry(block: list[str]) -> Entry:
    """Turn one raw entry block into an :class:`Entry`."""
    head = block[0].strip()
    parts = re.split(r"\s{2,}", head, maxsplit=1)
    spec = parts[0]
    inline = parts[1].strip() if len(parts) > 1 else ""

    # Long template: the body sits on the following lines at indent 10.
    body = [line[10:] if len(line) > 10 else line.strip() for line in block[1:]]
    # Short template: a wrapped continuation would land in the description
    # column; SatL never wraps, but absorb it rather than drop it.
    if inline and body:
        body = [line.strip() for line in block[1:]]

    lines = ([inline] if inline else []) + body
    entry = Entry(spec=spec, help="")

    # `Possible values:` sub-block (long template only).
    value_help: list[tuple[str, str]] = []
    prose: list[str] = []
    in_values = False
    for raw in lines:
        line = raw.rstrip()
        if line.strip() == "Possible values:":
            in_values = True
            continue
        if in_values:
            m = re.match(r"^\s*-\s+([^:]+):\s*(.*)$", line)
            if m:
                value_help.append((m.group(1).strip(), m.group(2).strip()))
                continue
            if not line.strip():
                continue
            in_values = False
        prose.append(line)

    # Standalone metadata lines (long template).
    kept: list[str] = []
    for line in prose:
        m = META_LINE_RE.match(line.strip())
        if m:
            absorb_meta(entry, m.group(1), m.group(2))
        else:
            kept.append(line)

    text = "\n".join(kept).strip()
    # Trailing metadata (short template), peeled right to left.
    while True:
        m = META_TAIL_RE.search(text)
        if not m:
            break
        absorb_meta(entry, m.group(1), m.group(2))
        text = text[: m.start()].rstrip()

    entry.help = re.sub(r"\n{3,}", "\n\n", text).strip()
    entry.value_help = value_help
    if value_help and not entry.values:
        entry.values = [name for name, _ in value_help]
    return entry


def absorb_meta(entry: Entry, key: str, value: str) -> None:
    key = key.rstrip("es") if key.startswith("alias") else key
    value = value.strip()
    if key == "env":
        entry.env = value.rstrip("=") or None
    elif key == "default":
        entry.default = value
    elif key == "possible values":
        entry.values = [v.strip() for v in value.split(",") if v.strip()]


def parse_help(text: str, path: list[str]) -> Help:
    """Parse a full ``--help`` page."""
    lines = text.splitlines()

    about: list[str] = []
    usage = ""
    sections: dict[str, list[str]] = {}
    current: str | None = None

    for line in lines:
        m = USAGE_RE.match(line)
        if m:
            usage = m.group(1).strip()
            current = None
            continue
        m = HEADER_RE.match(line)
        if m:
            current = m.group(1)
            sections[current] = []
            continue
        if current:
            sections[current].append(line)
        elif not usage:
            about.append(line)

    help_obj = Help(
        path=path,
        about="\n".join(about).strip(),
        usage=usage,
    )

    for block in split_entries(sections.get("Arguments", [])):
        help_obj.arguments.append(parse_entry(block))
    for block in split_entries(sections.get("Options", [])):
        help_obj.options.append(parse_entry(block))

    for block in split_entries(sections.get("Commands", [])):
        head = block[0].strip()
        parts = re.split(r"\s{2,}", head, maxsplit=1)
        name = parts[0]
        summary = parts[1].strip() if len(parts) > 1 else ""
        # Continuations, if clap ever wraps a summary.
        for extra in block[1:]:
            if extra.strip():
                summary = f"{summary} {extra.strip()}".strip()
        aliases: list[str] = []
        m = ALIAS_RE.search(summary)
        if m:
            aliases = [a.strip() for a in m.group(1).split(",") if a.strip()]
            summary = summary[: m.start()].rstrip()
        help_obj.commands.append(SubCommand(name=name, summary=summary, aliases=aliases))

    return help_obj


# --------------------------------------------------------------------------- #
# harvesting
# --------------------------------------------------------------------------- #


def run_help(binary: Path, path: list[str]) -> str:
    """Capture ``--help`` (never ``-h``: only the long form has the long help)."""
    argv = [str(binary), *path, "--help"]
    proc = subprocess.run(argv, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise SystemExit(
            f"gen_cli: `{' '.join(argv)}` exited {proc.returncode}\n{proc.stderr.strip()}"
        )
    return proc.stdout


def harvest(binary: Path, path: list[str], visited: set[tuple[str, ...]]) -> Help | None:
    """Walk the command tree depth-first, once per canonical path."""
    node = parse_help(run_help(binary, path), path)
    key = tuple(node.canonical)
    if key in visited:
        return None
    visited.add(key)

    for sub in node.commands:
        # Never recurse into an alias: `satl cluster` is `satl swarm`, and
        # walking both would emit the page twice under two names.
        child = harvest(binary, [*node.canonical, sub.name], visited)
        if child is not None:
            child.aliases = sub.aliases
            node.children.append(child)
    return node


# --------------------------------------------------------------------------- #
# overlay
# --------------------------------------------------------------------------- #


@dataclasses.dataclass
class Overlay:
    globals: list[str]
    groups: list[dict]
    diffs: list[dict]
    deny_flags: list[str]

    @classmethod
    def load(cls, path: Path) -> "Overlay":
        data = yaml.safe_load(path.read_text()) or {}
        return cls(
            globals=data.get("globals", []),
            groups=data.get("groups", []),
            diffs=data.get("diff", []),
            deny_flags=data.get("deny_flags", []),
        )

    def group_for(self, path: list[str]) -> dict | None:
        for group in self.groups:
            if any(list(p) == path for p in group.get("applies_to", [])):
                return group
        return None

    def groups_on_page(self, verb: str) -> list[dict]:
        return [g for g in self.groups if g.get("page") == verb]


def is_group_option(entry: Entry, group: dict) -> bool:
    name = entry.long or entry.spec
    return any(fnmatch.fnmatch(name, pat) for pat in group.get("match", []))


# --------------------------------------------------------------------------- #
# rendering
# --------------------------------------------------------------------------- #


def esc(text: str) -> str:
    """Make a string safe inside a Markdown table cell."""
    return text.replace("|", r"\|").replace("\n", "<br>")


def code(text: str) -> str:
    """A code span for prose, where a backtick span behaves."""
    return f"`{text}`".replace("|", r"\|")


def tcode(text: str) -> str:
    """A code span for a *table cell*, as raw HTML rather than backticks.

    Backticks cannot carry a pipe inside a table. python-markdown's tables
    extension splits the row on unescaped ``|`` before inline processing runs,
    and the ``\\|`` that survives that split is then inside a code span, where
    backslash escapes do not apply — so ``<worker|manager>`` renders literally
    as ``<worker\\|manager>``. Emitting ``<code>`` with a numeric entity keeps
    the pipe out of the splitter's way and out of the code span's reach at once.
    """
    escaped = (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "&#124;")
    )
    return f"<code>{escaped}</code>"


def anchor(path: list[str], prefix: str = "satl") -> str:
    return "-".join([prefix, *path])


def describe(entry: Entry) -> str:
    """The description cell: prose plus clap's metadata tail."""
    parts = [esc(entry.help) if entry.help else "—"]
    if entry.values and not entry.value_help:
        parts.append("Values: " + ", ".join(tcode(v) for v in entry.values))
    if entry.value_help:
        rendered = "; ".join(f"{tcode(n)} — {esc(d)}" for n, d in entry.value_help)
        parts.append(f"Values: {rendered}")
    if entry.default:
        parts.append(f"Default: {tcode(entry.default)}")
    if entry.env:
        parts.append(f"Environment: {tcode(entry.env)}")
    return "<br>".join(parts)


def table(title: str, header: str, entries: list[Entry], out: list[str]) -> None:
    if not entries:
        return
    if title:
        out.append(f"{title}\n")
    out.append(f"| {header} | Description |")
    out.append("| --- | --- |")
    for entry in entries:
        out.append(f"| {tcode(entry.spec)} | {describe(entry)} |")
    out.append("")


def visible_options(node: Help, overlay: Overlay) -> list[Entry]:
    """Everything but the global flags, which get one section per page."""
    return [e for e in node.options if (e.long or e.spec) not in overlay.globals]


def render_command(node: Help, overlay: Overlay, level: int, out: list[str]) -> None:
    """Render one command as a heading plus its sections."""
    full = " ".join(["satl", *node.canonical])
    out.append(f"{'#' * level} `{full}` {{ #{anchor(node.canonical)} }}\n")
    if node.about:
        out.append(f"{node.about}\n")
    if node.aliases:
        spelled = ", ".join(
            code(" ".join(["satl", *node.canonical[:-1], a])) for a in node.aliases
        )
        out.append(
            f'!!! note "Alias"\n\n'
            f"    {code(full)} is also spelled {spelled}. Both are the same command;"
            f" this reference documents the canonical spelling.\n"
        )
    out.append("```console\n$ " + " ".join(["satl", *node.usage.split()[1:]]) + "\n```\n")

    # `<COMMAND>` versus `[COMMAND]` in the usage line is the whole difference
    # between a pure namespace verb and one that also does something itself.
    # `satl ca` is the bracketed case: it prints the root CA on its own, and
    # carries real options of its own alongside a subcommand — hence a hybrid
    # page rather than a bare list of children.
    if node.children:
        if node.subcommand_required:
            out.append(
                f"{code(full)} is a group: it always takes one of the subcommands "
                f"below.\n"
            )
        else:
            out.append(
                f"{code(full)} is valid on its own — the subcommand is optional "
                f"(`[COMMAND]` in the usage line above). Its own options are listed "
                f"first, its subcommands after.\n"
            )

    table("**Arguments**", "Argument", node.arguments, out)

    group = overlay.group_for(node.canonical)
    options = visible_options(node, overlay)
    if group:
        grouped = [e for e in options if is_group_option(e, group)]
        options = [e for e in options if not is_group_option(e, group)]
    else:
        grouped = []

    table("**Options**", "Option", options, out)
    if grouped:
        out.append(
            f"{code(full)} also accepts the "
            f"[{group['title'].lower()} options](#{group['id']}) "
            f"({len(grouped)} flags), documented once below.\n"
        )
    if not node.children and not node.arguments and not options and not grouped:
        out.append("Takes no arguments or options of its own.\n")

    for child in node.children:
        render_command(child, overlay, level + 1, out)


def render_group(group: dict, sample: Help, overlay: Overlay, out: list[str]) -> None:
    """The shared-option section a ``#[command(flatten)]`` struct leaves no trace of."""
    out.append(f"## {group['title']} {{ #{group['id']} }}\n")
    if group.get("intro"):
        out.append(group["intro"].strip() + "\n")
    users = ", ".join(
        code("satl " + " ".join(p)) for p in group.get("applies_to", [])
    )
    out.append(f"Accepted by {users}, with identical meaning.\n")
    entries = [e for e in sample.options if is_group_option(e, group)]
    table("", "Option", entries, out)


def render_diff(diff: dict, tree: dict[tuple[str, ...], Help], overlay: Overlay,
                out: list[str]) -> None:
    """Set-difference two sibling commands: facts derived, judgement written."""
    left_path, right_path = list(diff["left"]), list(diff["right"])
    left, right = tree[tuple(left_path)], tree[tuple(right_path)]
    group = overlay.group_for(left_path) or overlay.group_for(right_path)

    def keys(node: Help) -> dict[str, Entry]:
        result: dict[str, Entry] = {}
        for entry in [*node.arguments, *visible_options(node, overlay)]:
            if group and is_group_option(entry, group):
                continue
            result[entry.key] = entry
        return result

    lk, rk = keys(left), keys(right)
    lname = "satl " + " ".join(left_path)
    rname = "satl " + " ".join(right_path)

    out.append(f"## {diff['title']} {{ #{diff['id']} }}\n")
    if diff.get("intro"):
        out.append(diff["intro"].strip() + "\n")

    shared = sorted(set(lk) & set(rk))
    only_left = sorted(set(lk) - set(rk))
    only_right = sorted(set(rk) - set(lk))

    out.append(
        f"Derived mechanically from the two commands' own `--help`, "
        f"with the {group['title'].lower() if group else 'shared'} options and the "
        f"global options excluded.\n"
    )
    out.append(f"| Accepted by | Options |")
    out.append("| --- | --- |")
    out.append(
        f"| both | {', '.join(tcode(k) for k in shared) if shared else '—'} |"
    )
    out.append(
        f"| {tcode(lname)} only | "
        f"{', '.join(tcode(k) for k in only_left) if only_left else '—'} |"
    )
    out.append(
        f"| {tcode(rname)} only | "
        f"{', '.join(tcode(k) for k in only_right) if only_right else '—'} |"
    )
    out.append("")

    pairs = diff.get("pairs", [])
    if pairs:
        out.append(
            "A set difference cannot see that two differently-named options do the "
            "same job. These pairings are asserted by hand in `overlay/cli.yml`:\n"
        )
        out.append(f"| {tcode(lname)} | {tcode(rname)} | Why they differ |")
        out.append("| --- | --- | --- |")
        for pair in pairs:
            out.append(
                f"| {tcode(pair['left'])} | {tcode(pair['right'])} | "
                f"{esc(pair.get('note', ''))} |"
            )
        out.append("")


def render_globals(root: Help, overlay: Overlay, out: list[str]) -> None:
    entries = [e for e in root.options if (e.long or e.spec) in overlay.globals]
    if not entries:
        return
    out.append("## Global options { #global-options }\n")
    out.append("Accepted by every `satl` command.\n")
    table("", "Option", entries, out)


def page_footer(version: str) -> str:
    return (
        f"\n---\n\n*Generated from `{version}` by `make gen`. Change it in the SatL "
        f"source or in `overlay/cli.yml`, never here.*\n"
    )


def page_header(version: str, stale: bool) -> list[str]:
    out = [BANNER, f"<!-- Source: {version} -->", ""]
    if stale:
        out += [
            '!!! danger "Generated from a stale binary"',
            "",
            "    This page was produced with `--allow-stale`: the `satl` binary it was",
            "    harvested from does not match the SatL source tree. Commands or flags",
            "    may be missing or wrong. Rebuild with `make gen-fresh`.",
            "",
        ]
    return out


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #


def check_deny(nodes: list[Help], overlay: Overlay) -> None:
    """Tripwire: a hidden flag must never reach a page.

    clap already omits ``hide = true`` arguments from ``--help``, so harvesting
    excludes them for free — which is precisely why this needs asserting rather
    than assuming: the day someone documents one by hand, or clap changes its
    mind, the build should stop.
    """
    if not overlay.deny_flags:
        return
    found: list[str] = []
    for node in nodes:
        for entry in [*node.options, *node.arguments]:
            name = entry.long or entry.spec
            if any(fnmatch.fnmatch(name, pat) for pat in overlay.deny_flags):
                found.append(f"{' '.join(['satl', *node.canonical])}: {name}")
    if found:
        raise SystemExit(
            "gen_cli: deny_flags tripwire fired — these must never be documented:\n  "
            + "\n  ".join(found)
        )


def flatten(node: Help, acc: list[Help]) -> None:
    acc.append(node)
    for child in node.children:
        flatten(child, acc)


def write(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines).rstrip() + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--satl", required=True, type=Path)
    parser.add_argument("--satld", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--overlay", required=True, type=Path)
    parser.add_argument(
        "--stale",
        action="store_true",
        help="mark every page as harvested from a binary that failed the drift check",
    )
    args = parser.parse_args()

    for binary in (args.satl, args.satld):
        if not binary.is_file():
            return fail(f"gen_cli: no such binary: {binary}\nRun `make gen-fresh`.")

    overlay = Overlay.load(args.overlay)
    version = subprocess.run(
        [str(args.satl), "--version"], capture_output=True, text=True, check=True
    ).stdout.strip()

    root = harvest(args.satl, [], set())
    assert root is not None
    nodes: list[Help] = []
    flatten(root, nodes)
    check_deny(nodes, overlay)
    tree = {tuple(n.canonical): n for n in nodes}

    args.out.mkdir(parents=True, exist_ok=True)
    for old in args.out.glob("*.md"):
        old.unlink()

    # One page per top-level verb.
    for verb in root.children:
        name = verb.canonical[0]
        out = page_header(version, args.stale)
        render_command(verb, overlay, 1, out)
        for group in overlay.groups_on_page(name):
            sample = tree[tuple(group["applies_to"][0])]
            render_group(group, sample, overlay, out)
        for diff in overlay.diffs:
            if list(diff["left"])[0] == name:
                render_diff(diff, tree, overlay, out)
        render_globals(root, overlay, out)
        out.append(page_footer(version))
        write(args.out / f"{name}.md", out)

    # Index: every verb, in the binary's own order.
    out = page_header(version, args.stale)
    out.append("# `satl` command reference\n")
    out.append(root.about + "\n" if root.about else "")
    out.append("```console\n$ " + " ".join(["satl", *root.usage.split()[1:]]) + "\n```\n")
    out.append("| Command | Description |")
    out.append("| --- | --- |")
    for verb in root.children:
        name = verb.canonical[0]
        summary = next(
            (c.summary for c in root.commands if c.name == name), verb.about
        )
        alias = (
            f"<br>Alias: {', '.join(tcode(a) for a in verb.aliases)}"
            if verb.aliases
            else ""
        )
        out.append(f"| [`satl {name}`]({name}.md) | {esc(summary)}{alias} |")
    out.append("")
    out.append(f"The daemon has [its own page](satld.md).\n")
    render_globals(root, overlay, out)
    out.append(page_footer(version))
    write(args.out / "index.md", out)

    # The daemon, through the same parser.
    satld_version = subprocess.run(
        [str(args.satld), "--version"], capture_output=True, text=True, check=True
    ).stdout.strip()
    daemon = parse_help(run_help(args.satld, []), [])
    out = page_header(satld_version, args.stale)
    out.append("# `satld` { #satld }\n")
    if daemon.about:
        out.append(daemon.about + "\n")
    out.append(f"```console\n$ {daemon.usage}\n```\n")
    table("**Options**", "Option", daemon.options, out)
    out.append(
        "`satld` is configured from a file, not from flags: see "
        "[`satld.toml`](../satld-toml.md).\n"
    )
    out.append(page_footer(satld_version))
    write(args.out / "satld.md", out)

    print(f"gen_cli: wrote {len(list(args.out.glob('*.md')))} pages to {args.out}")
    return 0


def fail(message: str) -> int:
    print(message, file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
